import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import GoogleProvider from "./GoogleOAuthProvider";
import UserDetailContextProvider from "@/context/UserDetailContext";
import ScreenSizeContextProvider from "@/context/ScreenSizeContext";
import DragDropLayoutElementProvider from "@/context/DragDropLayoutElement";
import EmailTemplateContextProvider from "@/context/EmailTemplateContext";
import SelectedElementProvider from "@/context/SelectedElementContext";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
          <GoogleProvider>
            <EmailTemplateContextProvider>
              <UserDetailContextProvider>
                <ScreenSizeContextProvider>
                  <DragDropLayoutElementProvider>
                    <SelectedElementProvider>
                      {children}
                    </SelectedElementProvider>
                  </DragDropLayoutElementProvider>
                </ScreenSizeContextProvider>
              </UserDetailContextProvider>
            </EmailTemplateContextProvider>
          </GoogleProvider>
        </ConvexClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
